# docs: https://github.com/knqyf263/pet?tab=readme-ov-file#configuration
[General]
  snippetfile = "~/.config/pet/snippet.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf --ansi"
  backend = "gist"
  sortby = "recency"

