[[snippets]]
  description = "clear uncessary branches"
  command = "git trim  --delete 'stray' --delete 'merged-local' -p main,stage,dev"
  output = ""

[[snippets]]
  description = "Show my public IP"
  command = "dig TXT +short ip @dns.toys"
  output = ""

[[snippets]]
  description = "change xlsx 비대면 바우처 format"
  command = "xlsx2csv \\(22년도\\)\\ 1월\\ 로그\\ 기록\\ 추출\\ 대상.xlsx | jq -sR 'split(\"\\n\")' | jq -r \"map(\\\"'\\\"+.+\\\"'\\\") | join(\\\",\\\")\" | pbcopy"
  output = ""
