
[[Snippets]]
  Description = "clear uncessary branches"
  Output = ""
  Tag = []
  command = "git trim  --delete 'stray' --delete 'merged-local' -p main,stage,dev"

[[Snippets]]
  Description = "Show my public IP"
  Output = ""
  Tag = ["network"]
  command = "dig TXT +short ip @dns.toys"

[[Snippets]]
  Description = "Show my public IP2"
  Output = ""
  Tag = ["network"]
  command = "curl ifconfig.me"

[[Snippets]]
  Description = "Show weather"
  Output = ""
  Tag = []
  command = "curl wttr.in"

[[Snippets]]
  Description = "Upgrade all brew packages"
  Output = ""
  Tag = ["brew", "mac"]
  command = "brew upgrade --greedy  && brew cleanup"

